winget install --accept-source-agreements --exact --silent --id "Microsoft.PowerShell"
winget install --accept-source-agreements --exact --silent --id "Microsoft.PowerToys"
winget install --accept-source-agreements --exact --silent --id "Microsoft.SQLServerManagementStudio"
winget install --accept-source-agreements --exact --silent --id "Microsoft.VisualStudio.2022.Community"
winget install --accept-source-agreements --exact --silent --id "Microsoft.VisualStudioCode"
