winget upgrade --accept-source-agreements --exact --silent --id "Microsoft.PowerShell"
winget upgrade --accept-source-agreements --exact --silent --id "Microsoft.PowerToys"
winget upgrade --accept-source-agreements --exact --silent --id "Microsoft.SQLServerManagementStudio"
winget upgrade --accept-source-agreements --exact --silent --id "Microsoft.VisualStudio.2022.Community"
winget upgrade --accept-source-agreements --exact --silent --id "Microsoft.VisualStudioCode"
