winget install --accept-package-agreements --accept-source-agreements --exact --silent --id '7zip.7zip'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Brave.Brave'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'DevToys-app.DevToys'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Git.Git'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'GitHub.cli'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Google.Chrome'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.PowerShell'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.PowerToys'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.SQLServerManagementStudio'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.VisualStudio.2022.Community'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.VisualStudioCode' --custom '/MERGETASKS="addcontextmenufiles,addcontextmenufolders,!runcode"'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Oracle.VirtualBox'