winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Chocolatey.Chocolatey'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.PowerShell'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.PowerToys'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.SQLServerManagementStudio'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.VisualStudio.2022.Community'
winget install --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.VisualStudioCode' --custom '/MERGETASKS="addcontextmenufiles,addcontextmenufolders,!runcode"'
