winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Chocolatey.Chocolatey'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Canonical.Ubuntu.2204'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.AppInstaller'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.DevHome'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.Edge'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.EdgeWebView2Runtime'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.OneDrive'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.PowerShell'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.PowerToys'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.SQLServerManagementStudio'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.Teams.Free'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.VCRedist.2015+.x64'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.VCRedist.2015+.x86'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.VisualStudio.2022.Community'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.VisualStudioCode' --custom '/MERGETASKS="addcontextmenufiles,addcontextmenufolders,!runcode"'
winget upgrade --accept-package-agreements --accept-source-agreements --exact --silent --id 'Microsoft.WindowsTerminal'
